/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <stdio.h>
int main()
{
    int previous, current, temp, sum;
    previous = 1;
    current = 2;
    sum = 0;
    while(current <= 4000000)
    {
        printf("%d\n", previous);
        if(current%2 == 0)
        {
            sum+=current;
            //printf("sum: %d\n", sum);
        }

        temp = previous;
        previous = current;
        current = temp + previous;

    }
    printf("sum: %d", sum);
    return 0;
}
